### PR TITLE
add @babel/runtime dependency

### LINKED ISSUE #7: add @babel/runtime as a peer dependecy
Hi!
I have a custom webpack resolver plugin (I have special `node_modules` path with special structure).
On my project I have `@rsuite/icons` as a dependency, but when I try to require it, it fails because it tries to require `@babel/runtime`, which is not a dependency / peer dependency of `@rsuite/icons` as it should be.

Can you please add it as a peer dependency ([here](https://github.com/rsuite/rsuite-icons/blob/master/package.json#L50))?
I tried to open a PR but I don't have permissions

```javascript
"peerDependencies": {
    "react": ">=16.8.0",
    "react-dom": ">=16.8.0",
    "@babel/runtime": ">=7.12.1"
  },
``` 

Thanks!

### PR DESCRIPTION
**Pull request by nadavbahalul**
Closes #7

### CODE REVIEW

**Comment by nadavbahalul** [comment]
@SevenOutman @simonguo can you please review? 🙏
(I can't add reviewers)

**Comment by SevenOutman** [comment]
Hi @nadavbahalul, thanks for contributing this edit! According to Babel docs about [`@babel/runtime`](https://babeljs.io/docs/babel-runtime) and [`@babel/plugin-transform-runtime`](https://babeljs.io/docs/babel-plugin-transform-runtime#installation) however, I think `@babel/runtime` should be a direct runtime dependency (declared in `dependencies` in package.json). WDYT?

**Review by nadavbahalul — COMMENTED** [review]
> Hi @nadavbahalul, thanks for contributing this edit! According to Babel docs about [`@babel/runtime`](https://babeljs.io/docs/babel-runtime) and [`@babel/plugin-transform-runtime`](https://babeljs.io/docs/babel-plugin-transform-runtime#installation) however, I think `@babel/runtime` should be a direct runtime dependency (declared in `dependencies` in package.json). WDYT?

@SevenOutman  done 👍

**Review by simonguo — APPROVED** [review]

**Comment by nadavbahalul** [comment]
@SevenOutman @simonguo do you know when this expected to be published?
I saw it wasn't published as part of the last `rsuite` release?
Thanks!

**Comment by SevenOutman** [comment]
It's been released in `1.0.3`.

**Pull request merged**
